# Generated by Django 4.2.30 on 2026-04-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_comment', 'New Comment'), ('new_like', 'New Like'), ('new_follower', 'New Follower'), ('moderation_action', 'Moderation Action'), ('story_removed', 'Story Removed'), ('report_resolved', 'Report Resolved'), ('badge_earned', 'Badge Earned'), ('new_story_published', 'New Story Published')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('new_comment', 'New Comment'), ('new_like', 'New Like'), ('new_follower', 'New Follower'), ('moderation_action', 'Moderation Action'), ('story_removed', 'Story Removed'), ('report_resolved', 'Report Resolved'), ('badge_earned', 'Badge Earned'), ('new_story_published', 'New Story Published')], max_length=20),
        ),
    ]
