# Generated by Django 4.2.29 on 2026-04-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='follow',
            name='follow_followed_idx',
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed', 'created_at'], name='follow_followed_date_idx'),
        ),
    ]
