# Generated by Django 4.2.30 on 2026-04-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follow_index_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_muted',
            field=models.BooleanField(default=False),
        ),
    ]
