# Generated by Django 4.2.29 on 2026-03-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stories/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=5)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes.')),
                ('original_filename', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='stories.story')),
            ],
            options={
                'db_table': 'media_items',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['story'], name='media_story_idx')],
            },
        ),
    ]
