# Generated by Django 4.2.29 on 2026-03-23 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Tag must be lowercase letters/digits separated by hyphens (e.g. ottoman-era).', regex='^[a-z0-9]+(-[a-z0-9]+)*$')])),
                ('is_predefined', models.BooleanField(default=False)),
                ('story_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_tags', to='stories.story')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_tags', to='tags.tag')),
            ],
            options={
                'db_table': 'story_tags',
                'indexes': [models.Index(fields=['tag'], name='storytag_tag_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='storytag',
            constraint=models.UniqueConstraint(fields=('story', 'tag'), name='unique_story_tag'),
        ),
    ]
