# Generated by Django 4.2.29 on 2026-03-25 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("narrative", models.TextField()),
                ("location_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_lng", models.DecimalField(decimal_places=6, max_digits=10)),
                ("location_name", models.CharField(max_length=255)),
                ("region", models.CharField(blank=True, max_length=255)),
                (
                    "time_type",
                    models.CharField(
                        choices=[
                            ("exact_year", "Exact Year"),
                            ("approximate_year", "Approximate Year"),
                            ("decade", "Decade"),
                            ("year_range", "Year Range"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.SmallIntegerField(blank=True, null=True)),
                ("year_start", models.SmallIntegerField(blank=True, null=True)),
                ("year_end", models.SmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("removed", "Removed"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("moderation_reason", models.TextField(blank=True, default="")),
                ("contributor_visible", models.BooleanField(default=True)),
                ("like_count", models.IntegerField(default=0)),
                ("save_count", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stories",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "submitted_at"], name="story_status_date_idx"
                    ),
                    models.Index(
                        fields=["status", "like_count"], name="story_status_likes_idx"
                    ),
                    models.Index(
                        fields=["location_lat", "location_lng"], name="story_coords_idx"
                    ),
                    models.Index(fields=["year"], name="story_year_idx"),
                    models.Index(
                        fields=["user", "status"], name="story_user_status_idx"
                    ),
                ],
            },
        ),
    ]
