# Generated by Django 4.2.29 on 2026-03-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('narrative_text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('removed', 'Removed')], default='draft', max_length=10)),
                ('removal_reason', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('place_name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('period_type', models.CharField(choices=[('exact', 'Exact Year'), ('range', 'Year Range'), ('decade', 'Decade')], default='exact', max_length=6)),
                ('start_year', models.SmallIntegerField()),
                ('end_year', models.SmallIntegerField(blank=True, null=True)),
                ('decade', models.SmallIntegerField(blank=True, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('save_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stories',
                'indexes': [models.Index(fields=['status', 'created_at'], name='story_status_date_idx'), models.Index(fields=['status', 'like_count'], name='story_status_likes_idx'), models.Index(fields=['latitude', 'longitude'], name='story_coords_idx'), models.Index(fields=['start_year'], name='story_start_year_idx'), models.Index(fields=['author', 'status'], name='story_author_status_idx')],
            },
        ),
    ]
