# Generated by Django 4.2.29 on 2026-03-24 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("narrative", models.TextField()),
                ("location_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_name", models.CharField(max_length=255)),
                (
                    "time_type",
                    models.CharField(
                        choices=[
                            ("exact_year", "Exact Year"),
                            ("approximate_year", "Approximate Year"),
                            ("decade", "Decade"),
                            ("year_range", "Year Range"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("year_start", models.IntegerField(blank=True, null=True)),
                ("year_end", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Published"), ("removed", "Removed")],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("moderation_reason", models.TextField(blank=True, default="")),
                ("contributor_visible", models.BooleanField(default=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stories",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
