# Generated by Django 4.2.29 on 2026-04-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_seed_predefined_tags'),
        ('stories', '0002_story_fulltext_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stories', through='tags.StoryTag', to='tags.tag'),
        ),
    ]
