# Generated by Django 4.2.30 on 2026-04-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='time_value',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='time_type',
            field=models.CharField(choices=[('exact_year', 'Exact Year'), ('approximate_year', 'Approximate Year'), ('decade', 'Decade'), ('year_range', 'Year Range'), ('exact_date', 'Exact Date')], max_length=20),
        ),
    ]
