# Generated by Django 4.2.29 on 2026-03-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_story_report',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_comment_report',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'story'), name='unique_story_report'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'comment'), name='unique_comment_report'),
        ),
    ]
